FROM node:20-slim AS base

# install pnpm
RUN npm install -g pnpm

WORKDIR /app

ARG NODE_ENV=production
ARG VITE_BACKEND_API_URL

ENV NODE_ENV=${NODE_ENV}
ENV VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL}

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm run build

EXPOSE 3000
