services:
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - telescope_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nginx_default
  backend:
    build: ./backend
    command: >
      bash -c "python manage.py flush --no-input &&
      python manage.py migrate &&
      python manage.py generate_fixtures &&
      gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3;"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ENV=${DJANGO_ENV:-development}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nginx_default
  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=${NODE_ENV:-production}
        - VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL}
    command: node .output/server/index.mjs
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL}
      - INTERNAL_BACKEND_API_URL=${INTERNAL_BACKEND_API_URL}
      - IS_DOCKER=${IS_DOCKER}
    depends_on:
      - backend
    networks:
      - nginx_default

networks:
  nginx_default:
    external: true

volumes:
  telescope_data:
