services:
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build: ./backend
    command: >
      bash -c "python manage.py flush --no-input &&
      python manage.py migrate &&
      python manage.py generate_fixtures &&
      if [ \"$${DJANGO_ENV}\" = \"production\" ]; then
        gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3;
      else
        python manage.py runserver 0.0.0.0:8000;
      fi"
    volumes:
      - ./backend:/app
    ports:
      - ${BACKEND_PORT:-8000}:8000
    environment:
      - DATABASE_URL=postgis://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ENV=${DJANGO_ENV:-development}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
